# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"\x0e\n\x0cQueryRequest\" \n\rQueryResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"\"\n\x0fWithdrawRequest\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"#\n\x10WithdrawResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0e\x44\x65positRequest\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"\"\n\x0f\x44\x65positResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9d\x01\n\x0e\x43ustomerBranch\x12(\n\x05Query\x12\r.QueryRequest\x1a\x0e.QueryResponse\"\x00\x12\x31\n\x08Withdraw\x12\x10.WithdrawRequest\x1a\x11.WithdrawResponse\"\x00\x12.\n\x07\x44\x65posit\x12\x0f.DepositRequest\x1a\x10.DepositResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYREQUEST._serialized_start=16
  _QUERYREQUEST._serialized_end=30
  _QUERYRESPONSE._serialized_start=32
  _QUERYRESPONSE._serialized_end=64
  _WITHDRAWREQUEST._serialized_start=66
  _WITHDRAWREQUEST._serialized_end=100
  _WITHDRAWRESPONSE._serialized_start=102
  _WITHDRAWRESPONSE._serialized_end=137
  _DEPOSITREQUEST._serialized_start=139
  _DEPOSITREQUEST._serialized_end=172
  _DEPOSITRESPONSE._serialized_start=174
  _DEPOSITRESPONSE._serialized_end=208
  _CUSTOMERBRANCH._serialized_start=211
  _CUSTOMERBRANCH._serialized_end=368
# @@protoc_insertion_point(module_scope)
